const btn = document.getElementById("btn");
const output = document.querySelector(".output");

let quote = [
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Don't watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "Opportunities don't happen, you create them.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The only place where success comes before work is in the dictionary.",
  "Don't be afraid to give up the good to go for the great.",
  "Happiness is not something readymade. It comes from your own actions.",
  "I never dreamed about success, I worked for it.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The only way to achieve the impossible is to believe it is possible.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "The road to success is dotted with many tempting parking spaces.",
  "The secret of success is to do the common things uncommonly well.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Don't let yesterday take up too much of today.",
  "The successful warrior is the average man, with laser-like focus.",
  "You are never too old to set another goal or to dream a new dream.",
  "The way to get started is to quit talking and begin doing.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Don't watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "Opportunities don't happen, you create them.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The only place where success comes before work is in the dictionary.",
  "Don't be afraid to give up the good to go for the great.",
  "Happiness is not something readymade. It comes from your own actions.",
  "I never dreamed about success, I worked for it.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The only way to achieve the impossible is to believe it is possible.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "The road to success is dotted with many tempting parking spaces.",
  "The secret of success is to do the common things uncommonly well.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Don't let yesterday take up too much of today.",
  "The successful warrior is the average man, with laser-like focus.",
  "You are never too old to set another goal or to dream a new dream.",
  "The way to get started is to quit talking and begin doing.",
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Don't watch the clock; do what it does. Keep going.",
  "The road to success and the road to failure are almost exactly the same.",
  "Opportunities don't happen, you create them.",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The only place where success comes before work is in the dictionary.",
  "Don't be afraid to give up the good to go for the great.",
  "Happiness is not something readymade. It comes from your own actions.",
  "I never dreamed about success, I worked for it.",
  "Success is not in what you have, but who you are.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "The only way to achieve the impossible is to believe it is possible.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "The road to success is dotted with many tempting parking spaces.",
  "The secret of success is to do the common things uncommonly well.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Don't let yesterday take up too much of today.",
  "The successful warrior is the average man, with laser-like focus.",
  "You are never too old to set another goal or to dream a new dream.",
  "The way to get started is to quit talking and begin doing."
]


btn.addEventListener("click",() =>{
  let random = Math.floor(Math.random()*quote.length);
  output.textContent = quote[random];
})